### ISSUE TITLE
code-box

### ISSUE THREAD

**Issue by La3tKnight** [TadavomnisT/MDEditor#4]
I think the code-box section has a very bright white background, which strains the eyes. It would be better if it were darker. 🤔

**Comment by TadavomnisT** [comment]
Thanks for reporting, will do.

**Comment by TadavomnisT** [comment]
@La3tKnight 

Fixed that, plus fixin some line-break problems:
![image](https://github.com/TadavomnisT/MDEditor/assets/63199745/67d559bd-34fb-4d7b-a816-bb6caf1e0266)

Now vs Then
